sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tB56ZLtFJeovA1syLbu
    access-key-secret: 2w1oCrngBE8Hx0EgUooXpHbNHZItiY
    bucket-name: java-ai-oneblink
